### ISSUE TITLE
Two identical tests

### ISSUE THREAD

**Issue by dycw** [Neoteroi/guardpost#5]
Hi, I discovered `blacksheep` and have been very impressed - then I wandered here. I noticed

https://github.com/Neoteroi/guardpost/blob/c3e9f6a2c52e96c0d0b7b6dd92002174144bb3fc/tests/test_authentication.py#L50-L61

are identical tests. I presume you were looking to test this guy:

https://github.com/Neoteroi/guardpost/blob/c3e9f6a2c52e96c0d0b7b6dd92002174144bb3fc/guardpost/authentication.py#L27-L38

**Comment by RobertoPrevato** [comment]
Hi! Thank you, indeed you are right.
I will fix soon, probably in the weekend. 

PS. soon I will share a nice demo / project template for my framework, which includes JWT Bearer authentication for users using access tokens issued by Azure Active Directory (applicable to any identity provider using OAuth).

**Comment by dycw** [comment]
Thanks! I am experienced in Python but just getting into get into web development - I've found Blacksheep to be extremely beautiful. I would love examples to get me going!

**Comment by RobertoPrevato** [comment]
Hi @dycw,
Since you wrote that you would love examples, I write to give you an update:

1. Today I published a library to simplify the use of SQLAlchemy in BlackSheep -> https://github.com/Neoteroi/BlackSheep-SQLAlchemy - in this repository you can also see an [example of API](https://github.com/Neoteroi/BlackSheep-SQLAlchemy/blob/main/tests/app.py) that uses db connections or ORM db sessions from SQLAlchemy; the tests folder also contain an example of ORM class applied using migrations with Alembic (applied in GitHub Actions)
2. A few days ago I started publishing an advanced demo project, with many features, but it's still a work in progress; [it's here](https://github.com/Neoteroi/Venezia/tree/dev)
